// Package furagu provides a simple wrapper around the flag package
// to support environment variable defaults.
//
// This package is designed to be used in a CLI application
// where you want to provide default values for flags from environment
// variables. It allows you to define flags and then parse them,
// using the environment variable values if they are set.
//
// The environment variable names are generated by taking the flag name,
// converting it to uppercase, and prefixing it with the provided prefix.
// For example, if you define a flag with the name "foo" and a prefix
// of "MYAPP", the environment variable will be "MYAPP_FOO".
package furagu

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"
)

// furaguFlag holds all the information about a flag
// to process it on parse instead of on define.
type furaguFlag struct {
	name         string
	usage        string
	defaultValue any
	ptr          any
}

var flags = make(map[string]furaguFlag)

// Parse parses the command line flags and sets the values.
// Must be called after all flags are defined.
//
// Panics if a environment variable is invalid.
func Parse(prefix string) {

	for name, f := range flags {
		usage := fmt.Sprintf("%s (env: %q)", f.usage, withPrefix(name, prefix))
		nameWithPrefix := withPrefix(name, prefix)

		switch f.defaultValue.(type) {
		case bool:
			flag.BoolVar(f.ptr.(*bool), name, boolFromEnv(nameWithPrefix, f.defaultValue.(bool)), usage)
		case int:
			flag.IntVar(f.ptr.(*int), name, intFromEnv(nameWithPrefix, f.defaultValue.(int)), usage)
		case string:
			flag.StringVar(f.ptr.(*string), name, strFromEnv(nameWithPrefix, f.defaultValue.(string)), usage)
		case float64:
			flag.Float64Var(f.ptr.(*float64), name, floatFromEnv(nameWithPrefix, f.defaultValue.(float64)), usage)
		case time.Duration:
			flag.DurationVar(f.ptr.(*time.Duration), name, durationFromEnv(nameWithPrefix, f.defaultValue.(time.Duration)), usage)
		default:
			panic(fmt.Sprintf("unsupported type %T for flag %s", f.defaultValue, name))
		}
	}

	flag.Parse()
}

func Bool(name string, value bool, usage string) *bool {
	p := new(bool)
	flags[name] = furaguFlag{name, usage, value, any(p)}
	return p
}

func Int(name string, value int, usage string) *int {
	p := new(int)
	flags[name] = furaguFlag{name, usage, value, any(p)}
	return p
}

func String(name string, value string, usage string) *string {
	p := new(string)
	flags[name] = furaguFlag{name, usage, value, any(p)}
	return p
}

func Float64(name string, value float64, usage string) *float64 {
	p := new(float64)
	flags[name] = furaguFlag{name, usage, value, any(p)}
	return p
}

func Duration(name string, value time.Duration, usage string) *time.Duration {
	p := new(time.Duration)
	flags[name] = furaguFlag{name, usage, value, any(p)}
	return p
}

func strFromEnv(envVar string, defaultVal string) string {
	if value := os.Getenv(envVar); value != "" {
		return value
	}
	return defaultVal
}

func intFromEnv(envVar string, defaultVal int) int {
	if value := os.Getenv(envVar); value != "" {
		intVal, err := strconv.Atoi(value)
		if err != nil {
			panic(fmt.Sprintf("environment variable `%s` has invalid value `%s`", envVar, value))
		}
		return intVal
	}
	return defaultVal
}

func boolFromEnv(envVar string, defaultVal bool) bool {
	if value := os.Getenv(envVar); value != "" {
		boolVal, err := strconv.ParseBool(value)
		if err != nil {
			panic(fmt.Sprintf("environment variable `%s` has invalid value `%s`", envVar, value))
		}
		return boolVal
	}

	return defaultVal
}

func floatFromEnv(envVar string, defaultVal float64) float64 {
	if value := os.Getenv(envVar); value != "" {
		floatVal, err := strconv.ParseFloat(value, 64)
		if err != nil {
			panic(fmt.Sprintf("environment variable `%s` has invalid value `%s`", envVar, value))
		}
		return floatVal
	}
	return defaultVal
}

func durationFromEnv(envVar string, defaultVal time.Duration) time.Duration {
	if value := os.Getenv(envVar); value != "" {
		durationVal, err := time.ParseDuration(value)
		if err != nil {
			panic(fmt.Sprintf("environment variable `%s` has invalid value `%s`", envVar, value))
		}
		return durationVal
	}
	return defaultVal
}

func withPrefix(name, prefix string) string {
	if prefix != "" {
		return strings.ToUpper(fmt.Sprintf("%s_%s", prefix, name))
	}
	return name
}
